---
- name: Download iTerm
  get_url: >
    url=https://iterm2.com/downloads/beta/iTerm2-2_9_20160510.zip
    dest={{ downloads_directory }}/iTerm2-2_9_20160510.zip

- name: Extract iTerm zip archive
  command: >
    chdir={{ downloads_directory }}
    unzip iTerm2-2_9_20160510.zip -d iTerm2-2_9_20160510
    creates=iTerm2-2_9_20160510

- name: Copy iTerm.app to Applications directory
  command: >
    cp -R {{ downloads_directory }}/iTerm2-2_9_20160510/iTerm.app /Applications
    creates=/Applications/iTerm.app
  sudo: yes
